# coding: utf-8

"""
    Collection Service

    API for managing collection

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictInt, StrictStr
from pydantic import Field
from product-list.models.productlist_order_by import ProductlistOrderBy
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ProductlistListProductListAssociationsRequest(BaseModel):
    """
    ProductlistListProductListAssociationsRequest
    """ # noqa: E501
    tenant_id: Optional[StrictStr] = Field(default=None, alias="tenantId")
    list_id: Optional[StrictStr] = Field(default=None, alias="listId")
    product_grn: Optional[StrictStr] = Field(default=None, alias="productGrn")
    page_size: Optional[StrictInt] = Field(default=None, alias="pageSize")
    page_token: Optional[StrictStr] = Field(default=None, alias="pageToken")
    order_by: Optional[List[ProductlistOrderBy]] = Field(default=None, alias="orderBy")
    __properties: ClassVar[List[str]] = ["tenantId", "listId", "productGrn", "pageSize", "pageToken", "orderBy"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProductlistListProductListAssociationsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in order_by (list)
        _items = []
        if self.order_by:
            for _item in self.order_by:
                if _item:
                    _items.append(_item.to_dict())
            _dict['orderBy'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ProductlistListProductListAssociationsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tenantId": obj.get("tenantId"),
            "listId": obj.get("listId"),
            "productGrn": obj.get("productGrn"),
            "pageSize": obj.get("pageSize"),
            "pageToken": obj.get("pageToken"),
            "orderBy": [ProductlistOrderBy.from_dict(_item) for _item in obj.get("orderBy")] if obj.get("orderBy") is not None else None
        })
        return _obj


