# coding: utf-8

"""
    Collection Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product-list.models.order_by_direction import OrderByDirection

class TestOrderByDirection(unittest.TestCase):
    """OrderByDirection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderByDirection(self):
        """Test OrderByDirection"""
        # inst = OrderByDirection()

if __name__ == '__main__':
    unittest.main()
