# coding: utf-8

"""
    Collection Service

    API for managing collection

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product-list.models.productlist_bulk_update_product_list_associations_request import ProductlistBulkUpdateProductListAssociationsRequest

class TestProductlistBulkUpdateProductListAssociationsRequest(unittest.TestCase):
    """ProductlistBulkUpdateProductListAssociationsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductlistBulkUpdateProductListAssociationsRequest:
        """Test ProductlistBulkUpdateProductListAssociationsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductlistBulkUpdateProductListAssociationsRequest`
        """
        model = ProductlistBulkUpdateProductListAssociationsRequest()
        if include_optional:
            return ProductlistBulkUpdateProductListAssociationsRequest(
                tenant_id = '',
                product_list_associations = [
                    product-list.models.productlist_bulk_update_product_list_associations_request_product_list_association.productlistBulkUpdateProductListAssociationsRequestProductListAssociation(
                        id = '', 
                        position = 56, )
                    ]
            )
        else:
            return ProductlistBulkUpdateProductListAssociationsRequest(
        )
        """

    def testProductlistBulkUpdateProductListAssociationsRequest(self):
        """Test ProductlistBulkUpdateProductListAssociationsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
