# coding: utf-8

"""
    Collection Service

    API for managing collection

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product-list.models.productlist_get_product_list_by_id_request import ProductlistGetProductListByIdRequest

class TestProductlistGetProductListByIdRequest(unittest.TestCase):
    """ProductlistGetProductListByIdRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductlistGetProductListByIdRequest:
        """Test ProductlistGetProductListByIdRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductlistGetProductListByIdRequest`
        """
        model = ProductlistGetProductListByIdRequest()
        if include_optional:
            return ProductlistGetProductListByIdRequest(
                tenant_id = '',
                id = ''
            )
        else:
            return ProductlistGetProductListByIdRequest(
        )
        """

    def testProductlistGetProductListByIdRequest(self):
        """Test ProductlistGetProductListByIdRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
