# coding: utf-8

"""
    Collection Service

    API for managing collection

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product-list.models.productlist_get_product_list_by_url_key_request import ProductlistGetProductListByUrlKeyRequest

class TestProductlistGetProductListByUrlKeyRequest(unittest.TestCase):
    """ProductlistGetProductListByUrlKeyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductlistGetProductListByUrlKeyRequest:
        """Test ProductlistGetProductListByUrlKeyRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductlistGetProductListByUrlKeyRequest`
        """
        model = ProductlistGetProductListByUrlKeyRequest()
        if include_optional:
            return ProductlistGetProductListByUrlKeyRequest(
                tenant_id = '',
                url_key = '',
                locale = ''
            )
        else:
            return ProductlistGetProductListByUrlKeyRequest(
        )
        """

    def testProductlistGetProductListByUrlKeyRequest(self):
        """Test ProductlistGetProductListByUrlKeyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
