# coding: utf-8

"""
    Collection Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product-list.models.productlist_update_product_list_request import ProductlistUpdateProductListRequest

class TestProductlistUpdateProductListRequest(unittest.TestCase):
    """ProductlistUpdateProductListRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductlistUpdateProductListRequest:
        """Test ProductlistUpdateProductListRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductlistUpdateProductListRequest`
        """
        model = ProductlistUpdateProductListRequest()
        if include_optional:
            return ProductlistUpdateProductListRequest(
                tenant_id = '',
                id = '',
                url_key = product-list.models.productlist_localized_text.productlistLocalizedText(
                    value = {
                        'key' : ''
                        }, ),
                attributes = {
                    'key' : {
                        'key' : None
                        }
                    },
                attributes_mask = ''
            )
        else:
            return ProductlistUpdateProductListRequest(
        )
        """

    def testProductlistUpdateProductListRequest(self):
        """Test ProductlistUpdateProductListRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
