# coding: utf-8

"""
    Collection Service

    API for managing collection

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product-list.models.productlist_create_product_list_request import ProductlistCreateProductListRequest

class TestProductlistCreateProductListRequest(unittest.TestCase):
    """ProductlistCreateProductListRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductlistCreateProductListRequest:
        """Test ProductlistCreateProductListRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductlistCreateProductListRequest`
        """
        model = ProductlistCreateProductListRequest()
        if include_optional:
            return ProductlistCreateProductListRequest(
                tenant_id = '',
                code = '',
                url_key = product-list.models.productlist_localized_text.productlistLocalizedText(
                    value = {
                        'key' : ''
                        }, ),
                entity_type = '',
                entity_code = '',
                attributes = {
                    'key' : {
                        'key' : None
                        }
                    }
            )
        else:
            return ProductlistCreateProductListRequest(
        )
        """

    def testProductlistCreateProductListRequest(self):
        """Test ProductlistCreateProductListRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
