# coding: utf-8

"""
    Collection Service

    API for managing collection

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product-list.models.productlist_delete_product_list_request import ProductlistDeleteProductListRequest

class TestProductlistDeleteProductListRequest(unittest.TestCase):
    """ProductlistDeleteProductListRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductlistDeleteProductListRequest:
        """Test ProductlistDeleteProductListRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductlistDeleteProductListRequest`
        """
        model = ProductlistDeleteProductListRequest()
        if include_optional:
            return ProductlistDeleteProductListRequest(
                tenant_id = '',
                id = ''
            )
        else:
            return ProductlistDeleteProductListRequest(
        )
        """

    def testProductlistDeleteProductListRequest(self):
        """Test ProductlistDeleteProductListRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
