# coding: utf-8

"""
    Collection Service

    API for managing collection

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product-list.models.productlist_get_product_lists_count_request import ProductlistGetProductListsCountRequest

class TestProductlistGetProductListsCountRequest(unittest.TestCase):
    """ProductlistGetProductListsCountRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductlistGetProductListsCountRequest:
        """Test ProductlistGetProductListsCountRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductlistGetProductListsCountRequest`
        """
        model = ProductlistGetProductListsCountRequest()
        if include_optional:
            return ProductlistGetProductListsCountRequest(
                tenant_id = ''
            )
        else:
            return ProductlistGetProductListsCountRequest(
        )
        """

    def testProductlistGetProductListsCountRequest(self):
        """Test ProductlistGetProductListsCountRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
