# coding: utf-8

"""
    Collection Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from product-list.models.set_product_list_associations_request_association import SetProductListAssociationsRequestAssociation

class TestSetProductListAssociationsRequestAssociation(unittest.TestCase):
    """SetProductListAssociationsRequestAssociation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetProductListAssociationsRequestAssociation:
        """Test SetProductListAssociationsRequestAssociation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetProductListAssociationsRequestAssociation`
        """
        model = SetProductListAssociationsRequestAssociation()
        if include_optional:
            return SetProductListAssociationsRequestAssociation(
                list_id = '',
                position = 56,
                product_grn = ''
            )
        else:
            return SetProductListAssociationsRequestAssociation(
        )
        """

    def testSetProductListAssociationsRequestAssociation(self):
        """Test SetProductListAssociationsRequestAssociation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
