# coding: utf-8

"""
    Collection Service

    API for managing collection

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from product-list.api.product_list_api import ProductListApi


class TestProductListApi(unittest.TestCase):
    """ProductListApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProductListApi()

    def tearDown(self) -> None:
        pass

    def test_bulk_update_product_list_associations(self) -> None:
        """Test case for bulk_update_product_list_associations

        Bulk update collection associations position
        """
        pass

    def test_create_product_list(self) -> None:
        """Test case for create_product_list

        Create Collection
        """
        pass

    def test_create_product_list_association(self) -> None:
        """Test case for create_product_list_association

        Create Collection/Product Association
        """
        pass

    def test_delete_product_list(self) -> None:
        """Test case for delete_product_list

        Delete Collection
        """
        pass

    def test_delete_product_list_association(self) -> None:
        """Test case for delete_product_list_association

        Delete Collection/Product Association
        """
        pass

    def test_get_product_list_associations_by_product_grn(self) -> None:
        """Test case for get_product_list_associations_by_product_grn

        Get Collection/Product Associations by Product GRN
        """
        pass

    def test_get_product_list_by_code(self) -> None:
        """Test case for get_product_list_by_code

        Get Collection by Code
        """
        pass

    def test_get_product_list_by_id(self) -> None:
        """Test case for get_product_list_by_id

        Get Collection by Id
        """
        pass

    def test_get_product_list_by_url_key(self) -> None:
        """Test case for get_product_list_by_url_key

        Get Collection by Url Key
        """
        pass

    def test_get_product_lists_count(self) -> None:
        """Test case for get_product_lists_count

        Get Collection Product Count
        """
        pass

    def test_list_product_list_associations(self) -> None:
        """Test case for list_product_list_associations

        List Collection/Product Associations
        """
        pass

    def test_list_product_lists(self) -> None:
        """Test case for list_product_lists

        List Collections
        """
        pass

    def test_search_product_lists(self) -> None:
        """Test case for search_product_lists

        Search Collections
        """
        pass

    def test_search_product_lists_by_ids(self) -> None:
        """Test case for search_product_lists_by_ids

        Search Collections by Ids
        """
        pass

    def test_update_product_list(self) -> None:
        """Test case for update_product_list

        Update Collection
        """
        pass


if __name__ == '__main__':
    unittest.main()
